apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: weather-check-workflow-dev
  namespace: argo
spec:
  schedule: "*/10 5-20 * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    imagePullSecrets:
      - name: argo-registry
    entrypoint: main
    templates:
    - name: main
      container:
        image: registry.tyreyalv.com/jenkins/weather-app:dev
        imagePullPolicy: Always
        command: ["python", "/app/temp_check.py"]
        imagePullSecrets:
        - name: argo-registry
        env:
          - name: OPENWEATHERMAP_API_KEY
            valueFrom:
              secretKeyRef:
                name: weather-app-secret
                key: OPENWEATHERMAP_API_KEY
          - name: DISCORD_WEBHOOK
            valueFrom:
              secretKeyRef:
                name: weather-app-secret
                key: DISCORD_WEBHOOK
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: weather-app-secret
                key: REDIS_HOST
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: weather-redis
                key: redis-password
